### ISSUE TITLE
can't open file aca-py

### ISSUE THREAD

**Issue by guilherme-funchal** [AnonSolutions/django-aries-community#16]
this error occurs after the manage start 

aries-django_1   | Stderr o_faber_college: python3: can't open file '../venv/bin/aca-py': [Errno 2] No such file or directory
aries-django_1   | Started, waiting for status check ...
aries-django_1   | Agent running with admin url http://aries-django:8051
aries-django_1   | Terminating aca-py process ...
aries-django_1   | Joining threads ...
aries-django_1   | Traceback (most recent call last):
aries-django_1   |   File "manage.py", line 21, in <module>
aries-django_1   |     main()
aries-django_1   |   File "manage.py", line 17, in main
aries-django_1   |     execute_from_command_line(sys.argv)
aries-django_1   |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
aries-django_1   |     utility.execute()
aries-django_1   |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
aries-django_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
aries-django_1   |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
aries-django_1   |     self.execute(*args, **cmd_options)
aries-django_1   |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
aries-django_1   |     output = self.handle(*args, **options)
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/management/commands/loads_orgs.py", line 107, in handle
aries-django_1   |     http_port=http_port, http_endpoint=http_endpoint, api_key=api_key, webhook_key=webhook_key
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/registration_utils.py", line 94, in org_signup
aries-django_1   |     http_port=http_port, http_endpoint=http_endpoint, api_key=api_key, webhook_key=webhook_key)
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/registration_utils.py", line 75, in org_provision
aries-django_1   |     provision_cred_defs_for_org(org, org_role)
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/registration_utils.py", line 34, in provision_cred_defs_for_org
aries-django_1   |     start_agent(org.agent)
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/agent_utils.py", line 192, in start_agent
aries-django_1   |     start_aca_py(agent.agent_name, config, agent.admin_endpoint, get_ADMIN_REQUEST_HEADERS(agent))
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/agent_utils.py", line 316, in start_aca_py
aries-django_1   |     detect_process(admin_endpoint, ADMIN_REQUEST_HEADERS)
aries-django_1   |   File "/home/aries/aries_community_demo/aries_community_demo/aries_community/agent_utils.py", line 270, in detect_process
aries-django_1   |     + f"Admin URL: {status_url}"

**Comment by guilherme-funchal** [comment]
It's working...
